### ISSUE TITLE
Refactor part 3: Empty out event handlers in control.lua

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#113]
## Task
For long event handlers in `control.lua`, break them down into smaller functions, and then move these functions into the appropriate lua modules if they exist. If appropriate modules do not yet exist, creating them will be the next step of the refactor. This third step should not interfere much with other changes because the event handlers already cannot be called from elsewhere in the code.

## Reasons
* To have a simple unified event handler eventually, individual event handlers need to be as simple as possible.
* When event handler actions have their own functions instead, they can be called from elsewhere when applicable.
* A shorter and simpler `control.lua` file is easier to understand and maintain.

**Comment by LevFendi** [comment]
Note: I should move entiry status reading to the newly created fa-info class as well...

**Comment by ahicks92** [comment]
Effectively dead.  We're doing this more piecemeal.  Will be handled by new cursor module, new UI layers thing, input refactor, etc etc.  There is no "part 3" anymore.
