### ISSUE TITLE
Better predictions of the Kruise Kontrol state

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#118]
This issue stems from the fact that FA is currently independently predicting what KK is doing rather than collecting the state info from it. It may or may not be possible to collect this info using a remote call, so if anyone can manage that then great. Perhaps we can call `Character:is_idle()`  in `character.lua`.
Otherwise, there are things that can be done to improve FA's independent predictions. I have already made some changes and published them to `next-update` on commit ab2d2e86a05263ee6a9226a5d7e5176f899179d0. Here is the latest:
1. KK assumed status is determined independently by FA when commanded. The same checks as those within the KK mod are used.
2. KK assumed status is checked every 1.5 seconds, and updated to "arrived"/"finished" based on checks unique to each state. These checks for now include only checking whether walking or driving is finished. More can be done for the other states. See the comment below.
3. KK assumed status is read out when it is determined or finished, and also every 7.5 seconds.

**Comment by LevFendi** [comment]
4. When building ghosts, KK stops when it runs out of nearby ghosts. The exact radius for this is unclear (The default is 64 but I don't know about exceptions). We can similarly make FA check for ghosts around the character, and test different ranges until we find an accurate one.
5. Similarly, when deconstructing, we can check a radius around the player for any entities marked for deconstruction. Same for upgrading and repairing, if those states are enabled.
6. When mining, we can perhaps assume that KK is done when the player has not moved in 1 second and is currently not mining.
7. When fighting, best to not assume anything.

**Comment by LevFendi** [comment]
When mining, we can perhaps assume that KK is done when the player has not moved in 1 second and is currently not mining.

**Comment by LevFendi** [comment]
When driving, a similar check as for walking can be done.

**Comment by LevFendi** [comment]
8. Regarding (3), it would be better to query the assumed KK status instead of having it read out by itself. Perhaps the keybind "CONTROL + ALT + ENTER" can be used.

**Comment by LevFendi** [comment]
Progress made to cover the suggestions above (commit 54aedea0f1dd75a9123b3ff837bc3b4cb39e47a9). Work can still be done regarding (6) and (8). I think this is sufficient progress for Milestone 11.2.

**Comment by ahicks92** [comment]
Why don't we just integrate it?  It shouldn't be that hard to do, is rarely updated, and I think there is possibly a Lua environment trick that may let us do so with minimal code changes.  It seems like  it would be way, way less work, even if we had to update it once a month for some reason, but it's not even that frequent.  Then we could drop the mouse and just ask it what it's doing.

Would also get us "walk to cursor" for "free".  By which I mean a low one-time cost.

**Comment by LevFendi** [comment]
I am all for integrating it, or just taking the logic our of it and re-using that, which is what the original dev suggested. I just found those to be difficult compared to what I did so far with the wrappers. In the long term, an interface with a custom version of that mod or a full integration of it is the only healthy way to go.

**Comment by ahicks92** [comment]
I'll look into it after UI.  The trick is that Lua environments let us hide our stuff from it, and prevent it from having name conflicts with us.  We can probably use an environment to wrap the mod, pass through Factorio's globals, and "reach in" to that environment if needed.  But honestly I'll probably just figure out if I can make it a proper library.  We will want the walking code for other things.

**Comment by ahicks92** [comment]
This is closed as WONTFIXX because my PR for KK #211 makes it irrelevant.  We don't do state predicting after that lands.
