### ISSUE TITLE
Add cursor skipping by hand preview size

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#163]
In connection to issue #133, one new feature for cursor skipping should be to skip by the width or height of the building or blueprint in hand.

This will make it easier to build in every direction at equal speed.

This feature will not apply for dimension sizes of just 1 or 2.

For now we can try adding this dimension check directly. It can be turned off by emptying the hand. In the future this might be added as a cursor skipping mode or a preference setting.

**Comment by LevFendi** [comment]
The feature has been integrated into cursor skipping. It is not a separate mode for now. Therefore this issue can be closed while #133 remains open.

**Comment by LevFendi** [comment]
Re-opened because the implementation as it stands is more confusing than helpful. The main discussion for this is on Issue #151.

**Comment by LevFendi** [comment]
The plan now is this feature being rebranded as an independent feature called "cursor rolling" and being assigned to the keys CONTROL + WASD. Started work on it in 4be5b9d05c712743c18cfa8205e748e613ecc210

**Comment by ahicks92** [comment]
I still think we should just call it move by preview.  No one will look sideways at the technical name, that's how screen readers etc. tend to name features.

I feel like rolling is creative, but I can't figure out how that word relates to what this is in any way.  My view is straightforward > fun given just how much we have at this point.  Putting cursor skipping into a very brief phrase that says what it does is probably not possible, so I do agree with that, but calling this move by preview is literally the entire manual on how to use it in 3 words.

**Comment by LevFendi** [comment]
You made a good case, agreed.
