### ISSUE TITLE
do something about dead enemies

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#167]
Skipping the templates because it's not a feature, but arguably not a bug, and if we call it an enhancement we'd be "enhancing" a whole hell of a lot.  Not sure what labels to add, but I've thrown the ones I think appropriate on.

When an enemy dies it will be on top of the tile.  This breaks getting to things lower down.  For example an enemy dying on a transport belt doesn't allow one to see the belt, cursor skipping into a dead enemy stops the skipping, they show up in the scanner, etc etc.  I'm not sure if any mod makes them important but as far as I know they aren't in Vanilla.  It's a bit important to know they're there just to know what was being attacked I guess.  I see 3 options:

- Get rid of them like logistic bots, except just poof they don't show up no matter what you do.  From the blind user's perspective they literally do not exist.
- Keep them, remove them from cursor skipping's consideration, and shift them to the "back" of the tile as far as our cursor and shift+f are concerned.
- Hide them away in all ways, and just say "transport belt with biter corpse" or "dirt with biter corpse" etc.

Probably more options than those, that's just what I came up with on the spot.  I've proposed having sounds for cursor movements before--this is a good example of where one might be useful for instance.  Seems like maybe I'm just failing to imagine, still the above are good fixes.

Also I don't know the cursor code nor do I know for sure that there's not some uber-popular mod that's like now you have alchemy and must put the biters in the cauldron (not at all thematic, but I have seen more ridiculous browsing the mod portal so...).  In other words I know neither what's easiest nor whether any choice has knock-on effects in 6 months.

Hopefully one of these is--I'd b happy with any of them personally.  Mostly I just want them to get out of my freaking way, I don't care how they do so.  I have a weak preference for knowing about it but I don't really know how I'd use the info.

**Comment by LevFendi** [comment]
Dead enemies are remnant entities, in the same type as tree stumps and destroyed buildings. You can clear them with `SHIFT + X`. They also fade away within a few minutes.

I think it is useful to have them but indeed they should not block cursor skipping. I will add an exception in cursor skipping code for all remnant types.

**Comment by ahicks92** [comment]
Ok, shift+x is useful. Would have never known that.  Basically that solves a large part of my problem.  Agreed that cursor skipping ignoring them would be an improvement however.

I do know they fade but because of how things work out there's an incentive to be as close as possible as fast as possible e.g. for repairs.  Sadly I couldn't find a config to make them fade faster.

**Comment by LevFendi** [comment]
As with #139, for remnants too we want the tile reading function to ignore them unless they are the only entities on the tile. A proper way to do this is being discussed on #139.

**Comment by LevFendi** [comment]
The latest situation with this issue is that cursor skipping ignores dead enemies. However, tile reading is a different issue and will be addressed with its own post later.

**Comment by LevFendi** [comment]
This has been resolved with the entity selection code rewrite in Update 0.13.0
