### ISSUE TITLE
Allow placing single ghosts from any distance

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#192]
The vanilla game allows placing entity ghosts at any distance. The mod allows this for blueprints but not single ghosts for buildings in hand. The restrictions on building by hand should be reviewed to allow exceptions for ghosts. 

Possibly, this action may require using Remote View but perhaps not. I will find out when I look into it.

**Comment by ahicks92** [comment]
duplicate  of #251
