### ISSUE TITLE
Remap character health check keybind to "G" and remap the train wagon connection keybind to something else

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#204]

**Comment by ahicks92** [comment]
Why?  Genuine question, not sarcasm.

**Comment by LevFendi** [comment]
The G key already pertains to armor equipment and it is easier to press than ALT + ]. This change was originally proposed shortly after this feature was released and maybe people got used to the existing keybind. We may want to do a poll about it.

**Comment by ahicks92** [comment]
Well, the thing to me is that you don't press either often.  I'm fine with whatever but will ask if we want to reserve [] in general for frequent things instead?  I'm not sure there's even a good reason to decouple after building and from that aspect if you build 5 trains you use it at most 10 times for the duration of your game.  alt+] seems valuable real estate.

**Comment by LevFendi** [comment]
Agreed

**Comment by LevFendi** [comment]
This was discussed on the general chat and agreed to use G. The changes were made in 376460c
