### ISSUE TITLE
shorten our localisation namespace names

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#212]
Right now it's `access.long-name-here`.  That's easy enough to read with a screen reader (e.g. this isn't a blindness issue).  It's very long to write all the time.  As we move away from English strings, we're going to have it freaking everywhere.  While we still can, let's switch to a shorter name. I like `fa` as we already use it pretty universally both in code and conversation.

This isn't the end of the world or anything but right now we're so bad at localisatino that it's easy to change our mind, so lets.

**Comment by ahicks92** [comment]
Took it myself. It's a find/replace.  Should take 10 minutes.  Maybe tomorrow.  Too tired and frustrated at stupid things to code right now.

Technically "big change".  Not really though.  I doubt I am going to wake up tomorrow to find out someone needed 100 strings or something all of a sudden.

**Comment by LevFendi** [comment]
The "access" into "fa" part sounds good to me, go ahead. I do not understand the rest: What are you proposing about the long key names? They need to be long so that they precisely explain what they are both for the coder and the translator to understand.

**Comment by ahicks92** [comment]
access adds a long thing to a long thing.  long-name-here is just a placeholder because I am lazy and didn't feel like digging up a real example.  I'm not going to be changing key names nor proposing that we should adopt a different style there.

**Comment by LevFendi** [comment]
Okay yes please go ahead with this
