### ISSUE TITLE
Add in-game console accessibility

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#214]
The modding API allows interfacing with the game console with the following features:
- `LuaBootStrap.raise_console_chat` makes your player publish a string in chat.
- Event `on_console_chat` provides the text string when a console message appears.
- Event `on_console_command` provides the text string when a console command is submitted. This is separate because the commands are not published in chat.

We can use these features to allow accessible multiplayer chat and also for providing feedback about what command the player has entered.

**Comment by ahicks92** [comment]
Also cool, I'd love this as the blind mod dev.  Thought we were going to need rcon for it.

**Comment by ahicks92** [comment]
Every time I see this I go no we can't support Switch why is this even an issue followed by like 5 seconds before I go o that.  So have a title tweak for clarity haha.

**Comment by LevFendi** [comment]
Added in 0.14.1.
This is a good start but we need API access to other console messages as well.
Furthermore, chat history is needed for effective chat support.
