### ISSUE TITLE
figure out what to do about the scanner needing a third level to represent some kinds of resource

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#230]
Basically, for forests right now the way we do things is you fumble around for a tree.  For infinite sources right now, the way we do things is we don't expose them as a cluster.  Both of these are suboptimal.  Ideally we'd have a third level to the scanner that would let one "zoom in" on ore patches.  Unfortunately we are kind of short on keys as we all know and I'm not sure there's enough uses for that.  I can invent a bunch (clustering buildings could have very interesting applications), but at least today we only have two.

This is annoying but fine for vanilla; however at some point someone's going to want to play with a mod that tries to do resource patches of infinite resources.  Also it's very annoying computing the clusters oneself by running over every entity.  For trees there is a degree of luck as to whether or not cursor skipping will catch one, which is even more of a special hell.

The only other alternative I've personally come up with is to zoom in based on distance.  For example oil is a patch and trees a foreest until yuou're within 20 tiles, then the scanner "expoands" those and unfolds them into the first level of resources, e.g. "trees" and "oil well" magically appear based on distance to "forest" and "oil patch 521%".

This isn't like super huge priority but it'd be nice and it'd be neat if someone has a good solution for it.  It'd also remove some special casing in the scanner.

**Comment by LevFendi** [comment]
There is a missing detail here: In the current system, all trees within 50 or so tiles are also scanned and added to the resources tab. This allows you to go to a forest and rescan to find the trees. You can consider this idea for the new system.

Also, oil wells were originally exempted from clustering not because they are infinite resource spots but because there are not that many of them. However, one can consider the same ideas as for trees, by making aggregate entities for them and exposing individual wells when within close proximity.

**Comment by ahicks92** [comment]
Yeah ok, I don't think we document the "within 50 tiles" thing, mostly I just found it weird that sometimes we get trees and didn't think much of it other than forest scanning code sometimes can't group.  The new scanner can happily do that, also for oil, and we can tack a "move closer to get more detail" message. I'll think on the wording.  To be clear new scanner doesn't exist, I just have a sort of finalizing plan and a bunch of code.

For context on oil the thing about oil patches: yeah they can be 10-20 tiles apart but in order to figure out how much is available the procedure (for how I do it anyway) is to teleport over there and then figure out the patch by toggling until it jumps far away, which isn't very efficient.  There's a big difference between finding 3 all at like 100% versus 10 at 200% etc.  If you get as far in your blind playthrough as setting up oil processing you'll probably see what I mean.  New scanner will preserve and hopefully accurately maintain a count for all patches (we will be able to say "iron ore, 30% remaining").

Suffice it to say there's a reason that new scanner wasn't a day haha.  But hopefully we will never ever have to do it again.  Should also account for 2.0 multi-surface. Anyway shrug, OT other than we can do any kind of grouping you ask for...

For the sake of our backlog I'll close this.  I thought that the whole "zooming" idea wasn't something we had a precedent for.  Given we don't want to take more keys in general "zooming" would be my preferred solution anyway, so yay easy discussion.
