### ISSUE TITLE
rotating a blueprint in hand loses some of the "temporary" status if it was from copy/paste, and can leak it into the inventory

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#231]
After a long time I've got a repro for how blueprints from copy/paste get into the inventory:

- copy something.
- rotate it in hand
- change the contents of the hand by specifically hitting the quickbar
- check inventory, there it is.

Seemed to be 100% reliable as of last night.

**Comment by LevFendi** [comment]
To narrow it down, can we also confirm the following:
1. Quickbar without rotation does not cause the issue
2. Rotation and then inventory stack swapping does not causs the issue

**Comment by ahicks92** [comment]
I can check the first later today.  Pretty sure I did at the time and it was fine.  I don't quickly know how to repro the second without flat out trying to modify the mod so if you have a procedure let me know.  The temporary-ness of an item stack isn't stored in the stack, it's stored in the player (e.g. probably we could flip the flag and nuke actual non-blueprint things even).

**Comment by LevFendi** [comment]
I will check these now

**Comment by LevFendi** [comment]
The issue has been found to be `refresh_blueprint_in_hand(pindex)` being called when you rotate the blueprint in hand to update the geometry information. I am working on a fix where I can both avoid this call and retain the needed info. It should not be too hard.
