### ISSUE TITLE
better reporting of curved rails

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#243]
A curved rail's unique orientation may be determined by the orientation of the curved rail alone, I believe.  If not, a corner's unique orientation may be determined by the two other rails as part of the turn.  I suggest that we name corners by their southwest-most direction to their northeast-most direction.  For example, "east to northeast curve".  Rising/falling are ambiguous on the curves themselves somewhat--or at least I can never get it right.

With 2.0 this will become much more important.

**Comment by LevFendi** [comment]
We can just list the both exit directions for each rotation, with the cardinal direction first. Example: "curved rail exits west and northeast".

**Comment by ahicks92** [comment]
I'd drop the word exits but this is basically you found a way to make what I said shorter so sure.

**Comment by LevFendi** [comment]
added in ad1e84d
