### ISSUE TITLE
allow fast travel menu while in a vehicle and rebind honking

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#246]
This is one of the reasons I don't drive.  If one wants to ask KK to go to a fast travel point one must get the fast travel menu open.  That's on v.  In cars, v becomes honking.  While thematic I guess, I don't think there's a a realistic practical use to honking but there is a realistic practical use to being able to get fast travel open to instruct Kruise Kontrol.

Though not an issue today maybe we also want to kill it on trains.  For example perhaps one day we have a fast travel "send this train to the closest station" thing.

If there's a good historical reason for this maybe we put honking somewhere else.  Alt+v or something, I dunno.

**Comment by LevFendi** [comment]
Completed in 0.14
