### ISSUE TITLE
reimplement belt support for 2.0

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#268]
2.0 has expanded and changed the transport belt API in two ways.  First, it is now possible to tell whether or not a belt has moved by indirectly comparing ids of item stacks.  Second, and more to the point, transport lines in the API now span morfe than one entity in some cases.  I list below what we need to do.  We may start off by simply disabling the code so that we have something which runs.

- First, we must define "transport line".  This needs a sighted person.  This has become a more official thing, as belts have now grown the ability to also read the whole line.
- Second, we must establish which methods on LuaTransportLine are related to the entity or the whole line.
- Once we know those, we must reimplement belt contents analysis tools.  We can leave total/upstream/downstream etc for later but we need to at least have current.
- Finally we have to decide what to do about total/upstream/downstream.

There is an idea of expanding the belt analyzer to crawl through underground belts and splitters.  But, given that we now have the whole line in the API and the concept is being directly exposed to non-modders, we may wish to instead not do that and make it match the circuit network.  This is my personal preference because the current belt analyzer can't easily tell one where the bulk of the items are, just that they exist in the belt system somewhere, and it can easily also pick up stuff on unrelated belts that happen to e.g. be behind a splitter and whatever and is thus "wrong" in some cases.  But we need to know what a "line" means, and that's not documented in the API docs.

**Comment by EphDoering** [comment]
From the circuit network tooltip:

> The signal is sent continuously as long as the items are on this belt or directly connected belts in front and in the back. Belts are cut on side-loading and inside of splitters.

I agree that our analysis should at least have a mode that agrees with the circuit network.

So about LuaTransportLine. They seem to be more like a viewer object that needs an internal transport line and an entity "owner". Everything talking about the contents is restricted to the contents within the entity. The internal transport line may extend for many entities, as is evidenced by the output_lines' owners being far away. However, since it doesn't appear that we can get the contents of the internal transport line up until the "output" it seems like the output_lines are rather useless for finding items on the belt. I haven't been able to come up with a use case for the input and output lines despite them seeming like they'd be ideal for walking the belt.

**Comment by ahicks92** [comment]
2.0 API adds line_length and get_line_item_positionas well as get_detailed_contents.  These from the docs may refer to more than just the current entity. That's what's unclear to me.

**Comment by EphDoering** [comment]
They do not. It appears that line_length represents how long the visible portion of the transport line within the entity is, which controls how many items can fit on that portion. The line_length for a straight belt is 1, but 0.4140625 for the inside lane of a curved belt. Disappointingly, there doesn't see to be a way to read the contents of the underground portion of an underground belt. The get_detailed_contents and other content related members only return items on the visible portion, which has a line length of 0.5.

The get_detailed_contents does allow us to check if a belt is flowing or stopped by looking at the positions over multiple ticks which is nice.

Oh, and in case the cut on side-loading wasn't clear enough, it only ends the belt that's pouring. The receiving line is not interrupted by side-loading.

For underground belts I think it's an unexpected parity of information between the visible screen and the API. I don't think I like it though. It means we can't count up to the same numbers the circuit network gets when underground belts are involved.

**Comment by ahicks92** [comment]
It has always been the case that the underground belts couldn't have their contents received, but if we match the circuit network then at least getting everything working should be simpler. Otherwise we can use the old behavior we have today assuming someone can even define what that is.  I don't like the behavior today because well define what it is.  Not what it's supposed to be, I know someone's going to say what it's supposed to be, but whatever it's doing isn't actually simple.

We should find out if circuit network is cut on underground belts and just not in the tooltip yet.  Can you test that somehow?

**Comment by EphDoering** [comment]
Yep, I did test it. There's graphics indicating which belts are being read so it was a quick test. It reads across undergrounds.

Further testing shows that as expected it does include the hidden items within the underground as well as all the above ground stuff.

**Comment by ahicks92** [comment]
I have dummied most of this code out for now, just wrt status of this. The adventure looms.

**Comment by ahicks92** [comment]
Now that most other things are done enough that the mod is at least running, I'm hoping to actually code this in the next couple days.  After much thought, I think these are roughly what we want.

1. Limit analysis to the current transport line, except  if hitting a un-filterd splitter with only one input before finding items.  No looking through sideloads or splitters with two inputs in "v1", though sideloads may be worth exploring later for sparse belts.
2. Evaluate a sparse belt by alternately going 1 back and 1 forward until items are found on a lane, then say "advanced circuit ahead" etc.
3. Don't consider inserters at all when doing belt heuristics.
4. If a belt sideloads into itself, and we detect that, warn the player it's a loop.
5. If none of this gets it then as a special case, use a splitter filter at the beginning of a belt because if a splitter filter is involved, the belt can only carry that item for the "can only" definition that ignores sideloads e.g. what we kind of have to use.

This is "less helpful" if you are new to the mod, because right now all the transport analysis runs away and grabs everything it can get it's greedy hands on.  Indeed I don't think anyone can even articulate the algorithm.  Unfortunately for advanced use cases--anything after "I want a splitter with a filter"--the current approach starts becoming meaningless.  It will happily say that things which aren't actually going to hit the current belt are involved.  We get two things from intentionally limiting this analysis.  First is that we can tell people how it works rather than just being like "yeah well".  Second is that because it's lighter weight and more obvious we can probably look back much further e.g. hundreds of units (funny thing about going backward in this interpretation is that you can't walk a loop because the loop points won't find a belt behind--only forward can loop. There are a couple cases where it can but they're easy to handle. But that's beside the point of this comment).

Later we can use the simplified interpretation to probably say things like "coal, 200 tiles behind, arrives in x seconds".

The splitter special case is because splitters can end up being used a lot for lane balancing in my experience.  For example you can use a splitter to "shift" half a lane to the other side and if you know what you're doing that lets you get furnace outputs balanced out right.  That particular case just comes down to having a very obvious interpretation where there's no other decision to be made, and me personally having used something like it a lot.

Ultimately we can go further eventually because if we are very, very careful it is possible to figure out whether or not any given item can get from any point in the belt network to any other point in the network.  The trouble is that this requires accounting for splitter filters and keeping track in the recursion.  I do actually think there's value in that sort of analysis, though not to me personally.  It's just not trivial to code or to test.

The difference between the belt analyzer and cursor announcement is just a cap on how far things go. Belt analyzer is unlimited, cursor is, idk, 10 or so? I'll decide that based off performance but given what the old things did here and what I expect to be able to get out of what is essentially "tiny scanner", 10 or so is probably basically instant for all intents.

If I am feeling ambitious I'll special case sideloads and merges to say what they sideload or merge, but that might be the bonus points task for later.

**Comment by ahicks92** [comment]
Well, this took more than a couple days for a variety of reasons, but is basically finished.  The remaining bits:

- Loaders.
- Cleaning up the wording, which got reimplemented but hasn't yet been made brief.
- Documentation so that whoever comes next doesn't have the same issues (I may literally be the world expert on Factorio's belt API at the moment--there's nothing anywhere written down).
- Testing. Dzsoker from Discord has been trying to do an early 2.0 playthrough so we have a good bit, but I'm not going to close this out till I've used it "for real".

Going to do docs tomorrow or so.  The rest can wait a while.  This is no longer 2.0-blocking, so changed the labels to 2.0.  Note that new belt code (save for splitter filters) is quality-aware.  There are probably remaining loose ends, but the codee of the belt code is documented and maintainable, with a design doc coming.

**Comment by ahicks92** [comment]
Closing this out.  Two issues to follow: one for loaders, one for space age stacked belts in the belt analyzer.  Neither blocks 2.0 base.
