### ISSUE TITLE
scan list sorting crashes (when you press N) if previously indexed entities have been destroyed

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#77]

**Comment by LevFendi** [comment]
Unable to reproduce this reliably. It happens only sometimes after you scan, kill enemies, and try to sort by pressing N. I know that the check for nil and invalid ents occurs before the actual sorting begins, so this bug requires better reproducability before we can fix it.

**Comment by ahicks92** [comment]
I'm taking this. Not sure when we can get to it.  Discussed it on Discord.  We can likely hack around the problem by just wrapping all sorts behind a function that cleans the arrays before sorting them.
