### ISSUE TITLE
Structure travel bug: Some neighboring structures are not logged.

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#89]
Some directly neighboring structures are not logged when they should be, such as machines next to inserters, or electric furnaces side by side.

This is an old bug from this old feature, so figuring it out would require me to figure out the entire feature.

**Comment by ahicks92** [comment]
@LevFendi we've deprecated this, should we wontfix.

**Comment by ahicks92** [comment]
Structure travel is dead.
