### ISSUE TITLE
Add basic support for ghost rail planner

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#90]
Oddly enough, "build as ghost" as a game input can be tied to a key although the normal "build" input cannot. Using this and some clever cursor manipulation (like in Remote View) we can use the game's built in ghost rail planner, which is identical to the rail planner except for placing ghosts instead.

I am working on adding basic support for this feature by making the mod do some checks around the feature's own checks. There is no direct control over the feature, so the following UX can be achieved:

1. With a rail in hand, if you SHIFT + LEFT BRACKET on the tip of a vertical or horizontal end rail, this feature activates correctly, regardless of where you stand. Hence checks have been added to make sure you can activated only at these locations. If the check fails, your hand is emptied, which automatically closes the planner. In addition, the failure case opens the rail builder menu as normal.
2. If you select an end point location too close to the start location and at a bad angle, the planner will try to build a big and ugly loop to make the rail still extend towards your point in a valid way. This will be highly confusing so I am adding the restriction for the end point being at least 50 tiles away. This will make the preview build rail ghosts that will have predictable shapes. If the check fails, your hand is emptied, which automatically closes the planner.
3. After passing the mod's checks at the end point, the planner's own checks apply. If the preview is invalid, nothing happens, otherwise the ghosts are placed, with a small confirmation sound. On top of the sound, I will make the mod check for the presence of ghost rails before and after the placement command so that it can confirm whether anything was built.
4. Despite everything, the valid rail placement may end up different from what you expect, because the planner finds that your desired path is unfeasible and offers an alternative path, which the mod cannot actually detect.

**Comment by ahicks92** [comment]
Consensus is Syntrax.  Briefly, the rail planner doesn't do "nice" things like straight lines with corners.  Because it is unpredictable, it isn't a useful tool to a blind user who will have no idea what it did, and if we wanted to lock it down to straight lines--well, we've already got that.

**Comment by LevFendi** [comment]
Syntrax is better but there may be hope for this idea later depending on what we find in 2.0 API. In any case we have more important tickets for now.
